### ISSUE TITLE
Google drive csv download issue

### ISSUE THREAD

**Issue by naraysa** [mira-space/MiraData#7]
Great work on the video caption data. 

There is an issue with the csv download from the Google drive link. It says "download quota exceeded for the file, so you can't download it at this time".

Would be great if you could have it shared on other platforms like HuggingFace as well.

**Comment by zzyfd** [comment]
Thanks for your advice and interests in our work ! We've updated the huggingface dataset  here: https://huggingface.co/datasets/TencentARC/MiraData.

**Comment by naraysa** [comment]
Thank you so much. Much appreciated
